name: 'de_capstone'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  de_capstone:
    staging:
      +materialized: view
      +schema: capstone_silver
    marts:
      +materialized: table
      +schema: capstone_gold